CREATE TABLE UNQASH_FACTURA_FOTO(
    C_ID UUID PRIMARY KEY,
    C_ID_FACTURA UUID NOT NULL UNIQUE,
    D_NOMBRE_ARCHIVO VARCHAR(255) NOT NULL,
    D_TIPO_CONTENIDO VARCHAR(100) NOT NULL,
    N_TAMANIO_BYTES BIGINT NOT NULL,
    CONTENIDO BYTEA NOT NULL,
    FE_FECHA_HORA_ALTA TIMESTAMP NOT NULL,
    CONSTRAINT FK_FACTURA_FOTO_FACTURA
        FOREIGN KEY (C_ID_FACTURA) REFERENCES UNQASH_FACTURA (C_ID)
);
