ALTER TABLE UNQASH_FACTURA
    ADD COLUMN C_ID_USUARIO_MODIFICACION UUID,
    ADD COLUMN FE_FECHA_HORA_MODIFICACION TIMESTAMP;

ALTER TABLE UNQASH_FACTURA
    ADD CONSTRAINT FK_FACTURA_USUARIO_MODIFICACION
        FOREIGN KEY (C_ID_USUARIO_MODIFICACION) REFERENCES UNQASH_USUARIO (C_ID);
