CREATE TABLE UNQASH_VENTA (
    C_ID UUID PRIMARY KEY,
    D_PRODUCTO VARCHAR(255) NOT NULL,
    N_MONTO NUMERIC(15, 2) NOT NULL,
    N_CANTIDAD INTEGER NOT NULL,
    C_ID_TIPO_COBRO UUID NOT NULL,
    CONSTRAINT FK_UNQASH_VENTA_TIPO_COBRO
        FOREIGN KEY (C_ID_TIPO_COBRO) REFERENCES UNQASH_TIPO_COBRO (C_ID)
);
