CREATE TABLE UNQASH_USUARIO (
    C_ID UUID PRIMARY KEY,
    D_APELLIDO VARCHAR(50) NOT NULL,
    D_NOMBRE VARCHAR(50) NOT NULL,
    N_DNI VARCHAR(8) NOT NULL UNIQUE,
    D_EMAIL VARCHAR(50) NOT NULL UNIQUE,
    N_TELEFONO VARCHAR(15) NOT NULL UNIQUE,
    D_CONTRASENA_HASH VARCHAR(255) NOT NULL,
    FECHA_HORA_ALTA TIMESTAMP NOT NULL,
    USUARIO_ALTA VARCHAR(50) NOT NULL
);
