ALTER TABLE UNQASH_VENTA
    ADD COLUMN C_ID_USUARIO UUID NOT NULL;

ALTER TABLE UNQASH_VENTA
    ADD CONSTRAINT FK_UNQASH_VENTA_USUARIO
        FOREIGN KEY (C_ID_USUARIO) REFERENCES UNQASH_USUARIO (C_ID);
