CREATE TABLE UNQASH_FACTURA(
    C_ID UUID PRIMARY KEY,
    D_PROVEEDOR VARCHAR(100) NOT NULL ,
    N_MONTO NUMERIC(10, 2)  NOT NULL ,
    FH_FECHA_FACTURA DATE NOT NULL ,
    D_DETALLE VARCHAR(200),
    FE_FECHA_HORA_ALTA TIMESTAMP NOT NULL ,
    C_ID_USUARIO_ALTA UUID NOT NULL,
    CONSTRAINT FK_FACTURA_USUARIO
       FOREIGN KEY (C_ID_USUARIO_ALTA) REFERENCES UNQASH_USUARIO (C_ID)

);