services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: unqash
      POSTGRES_USER: unqash
      POSTGRES_PASSWORD: unqash
    ports:
      - "5432:5432"
    volumes:
      - unqash_postgres_data:/var/lib/postgresql/data

volumes:
  unqash_postgres_data:
